INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,GX064)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,138spar)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,GBS85147)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,GBS1-NY)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,GBS2-NM)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,2603V/R)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,138P)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,GBS6)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,YM001)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,GX026)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,COH1)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,HN016)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,H002)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,09mas018883)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,NGBS572)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,GD201008-001)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,ILRI005)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,CNCTC)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,ILRI112)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,NEM316)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,NGBS061)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,GBS)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,2-22)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,SS1)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,SA20)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,SG-M1)
INSERT INTO genbank(genbank_id,organism_id,genome,genome_version)
VALUES(DEFAULT,SELECT id_genbank FROM organism WHERE id_organism = id_genbank,teste,A909)
