INSERT INTO analysis_type(analysis_type_id,analysis_name)
VALUES(DEFAULT,'Infernal_Rfam')
INSERT INTO analysis_type(analysis_type_id,analysis_name)
VALUES(DEFAULT,'Artemis')
INSERT INTO analysis_type(analysis_type_id,analysis_name)
VALUES(DEFAULT,'Mauve')
