INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,922412,922761,'-','TATGGAGCCGGTGGGAGTCGAACCCACGTCCAAACATCTGCTAATATATTTGTCTACAACTATAGGTTATGTATTGATTTAACTAGGTGATGACACATAACTCAAGCCCTCACATAGCGAGTCTATAAATCTCTTTTTAACTAACTAGACAGTAGCCAAACGTAGTTTGCTGATAAATAAGACCTTCTAGCAAAACGCAAACAATCTTGTGAAGATCACGCAGGCTGTTTTTTAGGCAGCTAATGCGTAAGAATTTGTATTTTTTGCAGTTATATTTAACTGGCATTTTACATCTGCCGATGAGTCGCGAAATATACCTCATAATGCCTGTCGAATCCGTAACGACCCC','tmRNA',7,2);




INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,739286,739400,'+','AATTTCTTCGGGGTCAGGTGAAAATCCTAACCGGCGGTATAGTCCGCGAGCTTTCGAGCATGAACTGGTGTGATTCCAGTACCGACAGTAAAGTCTGGATGAGAGAAGAATTCA','FMN',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,545553,545597,'-','GTCACTTAGTTTTTTATTCTGGGAAGTTTTCGAACCAGTCCGAG','PreQ1',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1312356,1312489,'-','TAAGCACAAAAAAATCGCACCTAAACCTAGACACGAAAGTACAATACGTTATTTTATAATGACGTTTTGTGCCTCGGTAGGAATATTATGAGCACTGCTCCCCTACTGTCTTAGGTCAGTTTCATCAGAAACT','L10_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,179028,179085,'+','TTTGTCGTCTGTCTAGGTTGAAATATTGTCCGACCTAGATATACAGCAGTTAAATCA','Lacto-rpoB',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,901774,901878,'-','AAAAAAGCACCGAATCGGTGCTCACTTTTTCAAGCTGAATACGGACTGGATTAAAAATCACTGCCTTATTTTAACGTGCTGTGCTGTTTCGAATAATTCCAACA','tracrRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,311668,312036,'+','TTTTTGGATAATCGCGTAGTATTGAGATACTATGAGGAAAGTCCATGCTAGCACTGGCTGTGATGCCAGTAGTGTTTGTGCTAGGCGAAAAAATAAGCCTAGGGAGATAGCTAGCTATCTTACGGCAAGCAAAAGGGCTAAGTCTTTGGATATGCCTGAATAGCTTTGAAAGTGCCACAGTGACGTAGTTTCTAGGGAAATCTAGAAAGTGGAACGCGGTAAACCCCTCAAGCTAGCAACCCAAACTTTGGTAGGGGCATGGGATAGTTGGAATGAGAACAATCTATCCTGACTGCTTTGCAGTAGACAGATGATTATCGAAAGAAACAATTCCTAGTTGTTTCTGGAACAAAACATGGCTTATAGAA','RNaseP_bact_b',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1961970,1962161,'+','CATTGCTGTGGCATACGAATCCACATCTAAGTGTTGACCGACTATTTCTTTGTATTTCGGGAAACGAAGTCATCTCTAGTGCGCAAGCCGTTAACACGCGGAAGCCACTTAAAGAGGTGCGAGTTACCCACCTGCTTATTTTGTGCGGGATCAATACAAAAAGTGGATCATCGGTGCCAATACAGCTTCCT','6S',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,570755,570836,'+','AAAGCCGTGTAAGGGAAAACCTTACGCACGGTTTGACGAGGGGTTTCTGAGGAGATGGCTCAAATCAGCGACCTACTCTAC','Intron_gpII',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1411733,1411878,'-','TTTGTCTTCTCCCATCCAGACTTTACTGTCGGTTGTGGAATCTCACCACATCAGCTTTCGCTCGCGGACTGATGCTTCACAACTGACAAATAAGTTGGAAGCGATTACCGCCGGTCGGGAATTACACCCTGCCCTGAAGACACCT','FMN',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,835190,835279,'+','TAGGACATTTGGGGTGCGTAACAGCTGAGATTATACCCATTGAACTTGATGCAGTTAGTACTGTCGAAGGGAAATGTGTGCCATTACAA','TPP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,815768,815866,'-','CCAATTCAAACCACAATTCCTACGCTCGTCCTAACGAGATCAGGTTAGAGGATTTTGCATATCTGCAATCTCAGCTCAAGGCACTCCCTTGTGTATTT','TPP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1094210,1094305,'-','CTATTTATTAGCTTACTTATTGTTAGACATTACGGTGTCTTGTAGAGACGCTAAGCCAATCCTCAGCATAAATAAGTAAATCATATATTTAATTG','Purine',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,408901,408986,'+','CTTTGGAGCAACATTTACTCGTGAAGTGGGTCAGGGGAGGAATCCAGCAGCCCTAAGCGATGCTAAATGTGTGCTCTTTTTATTT','Bacteria_small_SRP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1147544,1147676,'+','GACGGACTTCTGGAGAGACCTATAAGTAGCAACATCTTTGTATTGACACCAAGATGTGCTCTAGGCGCCGAAGGGGCAAGAAGAGTAAAACAACTCCTCCAATCTCTCAGGCAAAAGGACAGAAGCTAAAAG','Glycine',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1054599,1054718,'-','AGAAAAAAGCCTCCTAAAACAAGGAGGCTCTGCAAAATAGTAAGCTAGATAGGGAACTAACTTACTATTTGTTAACGCAATTCCTTGTTTGCCTCTCTGGACAATACCTTAAAGGATAT','PyrR',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,230706,230787,'+','GTATTGTTTACCCCATTTGTAAGGCCCCGGAACCTTTCAAATACTCTCGTGGACCGGAACATCCACACCTGTAAACAAAAA','L13_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1394081,1394206,'-','GAGAAAAACGAAAGCGGACTTGATAAATCAAGCCCGCACATATAATCTTCCTAGATGGAATCTTGACATGTTGGGCCAGACAACCTAAGTCGCAAGGCGAGAAGTTCTCACTTCTGCTTTTCTCA','L20_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1379715,1379794,'-','CCTCTGTGAAGACTCGCCTATAAATCGTGAGAGCCTTGCTCTACTTAATCTAACGATTTTCGCGCGGTTGCACAGGATG','L21_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,847184,847297,'+','GTGATATACTTAGTAAGTTGTTTTACACAACCCTTGATGCTTAGTTCCCTTTCATCAAGCATATTACAAACGTTAGAAGTGTTAACTATCTAAACGTTAAAGGAGAAATTATG','preQ1-II',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1593687,1593785,'-','AAAAAACCACACTGCTCGGAGTCAATCTCAGCAAACAATGTGGTTTATGGTGGTTTGTTAACTTAAATCATAACAGGTTTGATTTAAACTAACAAATC','23S-methyl',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1311262,1311411,'-','ACAAAAATCCTGCCAAAGAATTTTTGGCAGGATTTTTGGCAGGAAACCAAATCAATTTATCAGTTTCTATCAATCGCTTATCGCTCTCAAAGACTGGTAAATAGGGATTCCGCAATCTAATTATGATATGACTCTTATTTAAGAGTAAC','rli38',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1978493,1978676,'+','GAAATATGATATAATAATGAAGCAGAAAAGTTAAGACGGTGGCTCTTATTTCTGAAAGGTAGGTGGTCCCATGGGCAATTCATCAAAATCCAACAGAAAGGAGGAGCTAGATTTGTCTACCTTTGAGGTCTTAACACTCATGTTTATAGCAGGTAACTTCGTTATCGCTCTCGTGAAGTTAGT','rli28',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,90642,90714,'+','GAGTGTTATGATGATGGAATCAATCGATTCTTAGTCTAGCTCTGGTCTACCGCTGAGAATTATTCTCAGCGG','L17DE',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1063156,1063292,'-','GAAATTACAAGTAGTAGTAAGCTAAGGGCACCTTTTCAAGTGTGACAAGAAGGTTCACACAACTTATCAAGATCCGCTCCTGCGTTTATAATCTCCCTGCGCAATAGTGGTAAAACCACATATCGACTCATCGCAT','asd',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,100059,100157,'+','CGTTATAGCATAAAAACACGTTGCAGTTGGTAGTCTGCAAGCGTTCAGTGAACGTCAGTAACCTTCCCTCCAGGTCGTCCATTGCAATTTAATATTTA','yjdF',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1978735,1978819,'-','ATTTTTTAACGGTTATTTTCTGCCACCGTCTTAAACGGTTCTGCTAAGCAGTTGTTAGAAGCAACTGCTTTTTATTTACAATTA','RatA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1246074,1246164,'-','CCCTTCGTTCCATTTCCATTACAGAAACTTCATCACTACTATGGGTTCGGCTGACTTCTTGTCGTTCGTTGTTATTAGGTTTTACCCTCG','group-II-D1D4-1',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1246186,1246356,'-','GGACATCTTTCCTCGTTTACTCTCGTGATTTACGTATATAGGTTACGACTACCTATTTGGACTTTAGAGTTTATAGCCCCCTCATCCGCTATATACGCCTTCATATCACGTTTCTGTTCGTAGAGCCACGATTTCGCTATCCCTTCCTCTCCCCGCTACCTCACGATAGT','group-II-D1D4-3',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,568841,569017,'+','AACAGGTGAAAGTCCTGTCCTAACAATTAACCAGTTCGGTTAGGTAGCTATGGCATACGTATGCGGAGTAATCCAAATGCGGAAGCAATGCCGACTAACGTTATCCCCAGTAGGCTGATATTCATTGGTCTTATCTCAGTCCGTGGGAGCGAGCAAACCTACAGTCCGTAACGAAA','group-II-D1D4-4',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,518064,518209,'-','GTAGCAGATTACCTTGCTGAAGGTGAAAAAGTACAATTAATCGGTTTTGGTAACTTTGAAGTTCGTGAACGTGCAGCTCGTAAAGGTCGTAACCCACAAACTGGTGCAGAAATCGAAATTGCAGCATCAAAAGTTCCAGCATTTA','sau-50',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,2125821,2125887,'-','AACTCTCGAAAATTGTACGTCAAAAAGACTTACAAATTCCATGAGCTTTGACCATCATAGTTATTG','Spd-sr37',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,273558,273684,'+','CTGTTTTTTTAGCGAGCTCAAGGTAGTGAAAGTTGGGTAGAATAGGATGAATATTGGCACTTTTTAGTGAGTAAAAGTACAATCAAAAATGAAGTAATAAATTAGGGTGGAACCGCGTCTTTGACG','SpR19_sRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,373713,373841,'-','CTTGTTCTTCCTCCTTAAAAAATTTTTTCGTTGACATAAAGAAGAATAATCTCCTTCCAATCGTAAAATTGGCCATTCTTTTTCATTTCAACGAAATTATAGAACAGATATATTTTAAAACGTTTTCA','SSRC34',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AE009948'),2,1244456,1244615,'-','TAATTTTACTCCTTTATCAATGCTTTGTCAATGACAACTACCATCTTTTATCACATCAACTGAAGGGATAAGCAAAAGGCAATTGTTGACAGCTATTTGTCCTAACTTCTTTTTGATGAGGTAGCACAATCGAGTAGAGGCTAATCTCTAGCCCCTCTC','SSRC38',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,784995,785109,'+','AATTTCTTCGGGGTCAGGTGAAAATCCTAACCGGCGGTATAGTCCGCGAGCTTTCGAGCATGAACTGGTGTGATTCCAGTACCGACAGTAAAGTCTGGATGAGAGAAGAATTCA','FMN',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,600152,600196,'-','GTCACTTAGTTTTTTATTCTGGGAAGTTTTCGAACCAGTCCGAG','PreQ1',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1424496,1424629,'-','TAGGCACAAAAAAATCGCACCTAAACCTAGACACGAAAGTACAATACGTTATTTTATAATGACGTTTTGTGCCTCGGTAGGAATATTATGAGCACTGCTCCCCTACTGTCTTAGGTCAGTTTCATCAGAAACT','L10_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,178933,178990,'+','TTTGTCGTCTGTCTAGGTTGAAATATTGTCCGACCTAGATATACAGCAGTTAAATCA','Lacto-rpoB',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,945497,945601,'-','AAAAAAGCACCGAATCGGTGCTCACTTTTTCAAGCTGAATACGGACTGGATTAAAAATCACTGCCTTATTTTAACGTGCTGTGCTGTTTCGAATAGTTCTAACA','tracrRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1351516,1351681,'-','TAATTTTACTCCTTTATCAATGCTTTGTCAATGGCAACTACCATCTTTTATCACATCAACTGAAGGGATAAGCAAAAGGCAATTGTTGACAGCTATTTGTCCTAACTTCTTTTTGATGAGGTAGCACATATAAAAAAATAGAGAGAACCAAATTGGTTCTCTCTA','SSRC38',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,313608,313976,'+','TTTTTGGATAATCGCGTAGTATTGAGATACTATGAGGAAAGTCCATGCTAGCACTGGCTGTGATGCCAGTAGTGTTTGTGCTAGGCGAAAAAATAAGCCTAGGGAGATAGCTAGCTATCTTACGGCAAGCAAAAGGGCTAAGTCTTTGGATATGCCTGAATAGCTTTGAAAGTGCCACAGTGACGTAGTTTCTAGGGAAATCTAGAAAGTGGAACGCGGTAAACCCCTCAAGCTAGCAACCCAAACTTTGGTAGGGGCATGGGATAGTTGGAATGAGAACAATCTATCCTGACTGCTTTGCAGTAGACAGATGATTATCGAAAGAAACAATTCCTAGTTGTTTCTGGAACAAAACATGGCTTATAGAA','RNaseP_bact_b',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,2036264,2036455,'+','CATTGCTGTGGCATACGAATCCACATCTAAGTGTTGACCGACTATTTCTTTGTATTTCGGGAAACGAAGTCATCTCTAGTGCGCAAGCCGTTAACACGCGGAAGCCACTTAAAGAGGTGCGAGTTACCCACCTGCTTATTTTGTGCGGGATCAATACAAAAAGTGGATCATCGGTGCCAATACAGCTTCCT','6S',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,965427,965776,'-','TATGGAGCCGGTGGGAGTCGAACCCACGTCCAAACATCTGCTAATATATTTGTCTACAACTATAGGTTATGTATTGATTTAACTAGGTGATGACACATAACTCAAGCCCTCACATAGCGAGTCTATAAATCTCTTTTTAACTAACTAGACAGTAGCCAAACGTAGTTTGCTGATAAATAAGACCTTCTAGCAAAACGCAAACAATCTTGTGAAGATCACGCAGGCTGTTTTTTAGGCAGCTAATGCGTAAGAATTTGTATTTTTTGCAGTTATATTTAACTGGCATTTTACATCTGCCGATGAGTCGCAAAATATACCTCATAATGCCTGTCGAATCCGTAACGACCCC','tmRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1522882,1523027,'-','TTTGTCTTCTCCCATCCAGACTTTACTGTCGGTTGTGGAATCTCACCACATCAGCTTTCGCTCGCGGACTGATGCTTCACAACTGACAAATAAGTTGGAAGCGATTACCGCCGGTCGGGAATTACACCCTGCCCTGAAGACACCT','FMN',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,879269,879358,'+','TAGGACATTTGGGGTGCGTAACAGCTGAGATTATACCCATTGAACTTGATACAGTTAGTACTGTCGAAGGGAAATGTGTGCCATTACAA','TPP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,860206,860304,'-','CCAATTCAAACCACAATTCCTACGCTCGTCCTAACGAGATCAGGTTAGAGGATTTTGCATATCTGCAATCTCAGCTCAAGGCACTCCCTTGTGTATTT','TPP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1163395,1163490,'-','CTATTTATTAGCTTACTTATTGTTAGACATTACGGTGTCTTGTAGAGACGCTAAGCCAATCCTCAGCATAAATAAGTAAATCATATATTTAATTG','Purine',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,457917,458002,'+','CTTTGGAGCAACATTTACTCGTGAAGTGGGTCAGGGGAGGAATCCAGCAGCCCTAAGCGATGCTAAATGTGTGCTCTTTTTATTT','Bacteria_small_SRP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1250640,1250772,'+','GACGGACTTCTGGAGAGACCTATAAGTAGCAACATCTTTGTATTGACACCAAGATGTGCTCTAGGCGCCGAAGGGGCAAGAAGAGTAAAACAACTCCTCCAATCTCTCAGGCAAAAGGACAGAAGCTAAAAG','Glycine',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1124364,1124483,'-','AGAAAAAAGCCTCCTAAAACAAGGAGGCTCTGCAAAATAGTAAGCTAGATAGGGAACTAACTTACTATTTGTTAACGCAATTCCTTGTTTGCCTCTCTGGACAATACCTTAAAGGATAT','PyrR',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,231806,231887,'+','GTATTGTTTACCCCATTTGTAAGGCCCCGGAACCTTTCAAATACTCTCGTGGACCGGAACATCCACACCTGTAAACAAAAA','L13_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1505228,1505353,'-','GAGAAAAACGAAAGCGGACTTGATAAATCAAGCCCGCACATATAATCTTCCTAGATGGAATCTTGACATGTTGGGCCAGACAACCTAAGTCGCAAGGCGAGAAGTTCTCACTTCTGCTTTTCTCA','L20_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1490863,1490942,'-','CCTCTGTGAAGACTCGCCTATAAATCGTGAGAGCCTTGCCCTACTTAATCTAACGATTTTCGCGCGGTTGCACAGGATG','L21_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,891258,891371,'+','GTGATATACTTAGTAAGTTGTTTTACACAACCCTTGATGCTTAGTTCCCTTTCATCAAGCATATTACAAACGTTAGAAGTGTTAACTATCTAAACGTTAAAGGAGAAATTATG','preQ1-II',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1698124,1698222,'-','AAAAAACCACACTGCTCGGAGTCAATCTCAGCAAACAATGTGGTTTATGGTGGTTTGTTAACTTAAATCATAACAGGTTTGATTTAAACTAACAAATC','23S-methyl',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1423402,1423551,'-','ACAAAAATCCTGCCAAAGATTTTTTGGCAGGATTTTTGGCAGGAAACCGAATCAATTTATCAGTTTCTTCAAATCGCTATGAGCTCTAAAAGACTGGTAAATCGGGATTCCGCTCTCAAATCGCTATGTGCTTCTTATTTAAGAGTAAC','rli38',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1371735,1371884,'-','AATAAAACCCCACCAAGATTTAATCTTGGTGGGGTTTTGGTGGGGAATGATAACATTCTCCCGATTTTTTATCGCTCTAAGCAATTCTAAAACCTTGATTTACTAGGCTTCCGCAATCAAATTGCGATACTCTATTATTTAAGAGTAAC','rli38',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,503865,504049,'-','CTAACTTCACGAGAGCGATAACGAAGTTACCTGCTATAAACATGAGTGTTAAGACCTCAAAGGTAGACAAATCTAGCTCCTCCTTTCTGTTGGATTTTGATGAATTGCCCATGGGCACCACCTACCTTTCAGAAATAAGAGCCACCGTCTTAACTTTTCTGCCTTTTTATTATAACATACCGTA','rli28',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,90858,90930,'+','GAGTGTTATGATGATGGAATCAATCGATTCTTAGTCTAGCTCTGGTCTACCGCTGAGAATTATTCTCAGCGG','L17DE',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,1133777,1133913,'-','GAAATTACAAGTAGTAGTAAGCTAAGGGCACCTTTTCAAGTGTGACAAGAAGGTTCACACAACTTATCAAGATCCGCTCCTGCGTTTATAATCTCCCTGCGCAATAGTGGTAAAACCACATATCGACTCATCGCAT','asd',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,100087,100185,'+','CGTTATAGCATAAAAACACGTTGCAGTTGGTAGTCTGCAAGCGTTCAGTGAACGTCAGTAACCTTCCCTCCAGGTCGTCCATTGCAATTTAATATTTA','yjdF',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,503719,503806,'+','AATAAAAATAGAAAAGGGCAGTTGCGGAAACAACTACCCAATGCAGAACCGTTTAAGACGGTGGCAGAAAATAACCGTTAAAAAATA','RatA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,572663,572808,'-','GTAGCAGATTACCTTGCTGAAGGTGAAAAAGTACAATTAATCGGTTTTGGTAACTTTGAAGTTCGTGAACGTGCAGCTCGTAAAGGTCGTAACCCACAAACTGGTGCAGAAATCGAAATTGCAGCATCAAAAGTTCCAGCATTTA','sau-50',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,2177113,2177179,'-','AACTCTCGAAAATTGTACGTCAAAAAGACTTACAAATTCCATGAGCTTTGACCATCATAGTTATTG','Spd-sr37',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,275505,275631,'+','CTGTTTTTTTAGCGAGCTCAAGGTAGTGAAAGTTGGGTAGAATAGGATGAATATTGGCACTTTTTAGTGAGTAAAAGTACAATCAAAAATGAAGTAATAAATTAGGGTGGAACCGCGTCTTTGACG','SpR19_sRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'AL732656'),2,375652,375780,'-','CTTGTTCTTCCTCCTTAAAAAATTTTTTCGTTGACATAAAGAAGAATAATCTCCTTCCAATCGTAAAATTGGCCATTCTTTTTCATTTCAACGAAATTATAGAACAGATATATTTTAAAACGTTTTCA','SSRC34',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,999964,1000313,'-','TATGGAGCCGGTGGGAGTCGAACCCACGTCCAAACATCTGCTAATATATTTGTCTACAACTATAGGTTATGTATTGATTTAACTAGGTGATGACACATAACTCAAGCCCTCACATAGCGAGTCTATAAATCTCTTTTTAACTAACTAGACAGTAGCCAAACGTAGTTTGCTGATAAATAAGACCTTCTAGCAAAACGCAAACAATCTTGTGAAGATCACGCAGGCTGTTTTTTAGGCAGCTAATGCGTAAGAATTTGTATTTTTTGCAGTTATATTTAACTGGCATTTTACATCTGCCGATGAGTCGCGAAATATACCTCATAATGCCTGTCGAATCCGTAACGACCCC','tmRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,817263,817377,'+','AATTTCTTCGGGGTCAGGTGAAAATCCTAACCGGCGGTATAGTCCGCGAGCTTTCGAGCATGAACTGGTGTGATTCCAGTACCGACAGTAAAGTCTGGATGAGAGAAGAATTCA','FMN',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,615164,615208,'-','GTCACTTAGTTTTTTATTCTGGGAAGTTTTCGAACCAGTCCGAG','PreQ1',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1320018,1320151,'-','TAGGCACAAAAAAATCGCACCTAAACCTAGACACGAAAGTACAATACGTTATTTTATAATGACGTTTTGTGCCTCGGTAGGAATATTATGAGCACTGCTCCCCTACTGTCTTAGGTCAGTTTCATCAGAAACT','L10_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,188955,189012,'+','TTTGTCGTCTGTCTAGGTTGAAATATTGTCCGACCTAGATATACAGCAGTTAAATCA','Lacto-rpoB',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,979987,980091,'-','AAAAAAGCACCGAATCGGTGCTCACTTTTTCAAGCTGAATACGGACTGGATTAAAAATCACTGCCTTATTTTAACGTGCTGTGCTGTTTCGAATAATTCCAACA','tracrRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1298738,1298903,'-','TAATTTTACTCCTTTATCAATGCTTTGTCAATGGCAACTACCATCTTTTATCACATCAACTGAAGGGATAAGCAAAAGGCAATTGTTGACAGCTATTTGTCCTAACTTCTTTTTGATGAGGTAGCACATATAAAAAAATAGAGAGAACCAAATTGGTTCTCTCTA','SSRC38',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,321749,322117,'+','TTTTTGGATAATCGCGTAGTATTGAGATACTATGAGGAAAGTCCATGCTAGCACTGGCTGTGATGCCAGTAGTGTTTGTGCTAGGCGAAAAAATAAGCCTAGGGAGATAGCTAGCTATCTTACGGCAAGCAAAAGGGCTAAGTCTTTGGATATGCCTGAATAGCTTTGAAAGTGCCACAGTGACGTAGTTTCTAGGGAAATCTAGAAAGTGGAACGCGGTAAACCCCTCAAGCTAGCAACCCAAACTTTGGTAGGGGCATGGGATAGTTGGAATGAGAACAATCTATCCTGACTGCTTTGCAGTAGACAGATGATTATCGAAAGAAACAATTCCTAGTTGTTTCTGGAACAAAACATGGCTTATAGAA','RNaseP_bact_b',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1938825,1939016,'+','CATTGCTGTGGCATACGAATCCACATCTAAGTGTTGACCGACTATTTCTTTGTATTTCGGGAAACGAAGTCATCTCTAGTGCGCAAGCCGTTAACACGCGGAAGCCACTTAAAGAGGTGCGAGTTACCCACCTGCTTATTTTGTGCGGGATCAATACAAAAAGTGGATCATCGGTGCCAATACAGCTTCCT','6S',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1418412,1418557,'-','TTTGTCTTCTCCCATCCAGACTTTACTGTCGGTTGTGGAATCTCACCACATCAGCTTTCGCTCGCGGACTGATGCTTCACAACTGACAAATAAGTTGGAAGCGATTACCGCCGGTCGGGAATTACACCCTGCCCTGAAGACACCT','FMN',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,913402,913491,'+','TAGGACATTTGGGGTGCGTAACAGCTGAGATTATACCCATTGAACTTGATGCAGTTAGTACTGTCGAAGGGAAATGTGTGCCATTACAA','TPP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,892419,892517,'-','CCAATTCAAACCACAATTCCTACGCTCGTCCTAACGAGATCAGGTTAGAGGATTTTGCATATCTGCAATCTCAGCTCAAGGCACTCCCTTGTGTATTT','TPP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1149089,1149184,'-','CTATTTATTAGCTTACTTATTGTTAGACATTACGGTGTCTTGTAGAGACGCTAAGCCAATCCTCAGCATAAATAAGTAAATCATATATTTAATTG','Purine',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,418981,419066,'+','CTTTGGAGCAACATTTACTCGTGAAGTGGGTCAGGGGAGGAATCCAGCAGCCCTAAGCGATGCTAAATGTGTGCTCTTTTTATTT','Bacteria_small_SRP',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,2043963,2044032,'+','CGCACATCTTGTTGTCTGATTATTGATTTTTCGCGAAACCATTTGATCATATGACAAGATGTGTATCCA','RNA-OUT',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1203251,1203383,'+','GACGGACTTCTGGAGAGACCTATAAGTAGCAACATCTTTGTATTGACACCAAGATGTGCTCTAGGCGCCGAAGGGGCAAGAAGAGTAAAACAACTCCTCCAATCTCTCAGGCAAAAGGACAGAAGCTAAAAG','Glycine',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1110252,1110371,'-','AGAAAAAAGCCTCCTAAAACAAGGAGGCTCTGCAAAATAGTAAGCTAGATAGGGAACTAACTTACTATTTGTTAACGCAATTCCTTGTTTGCCTCTCTGGACAATACCTTAAAGGATAT','PyrR',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,240256,240337,'+','GTATTGTTTACCCCATTTGTAAGGCCCCGGAACCTTTCAAATACTCTCGTGGACCGGAACATCCACACCTGTAAACAAAAA','L13_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1400759,1400884,'-','GAGAAAAACGAAAGCGGACTTGATAAATCAAGCCCGCACATATAATCTTCCTAGATGGAATCTTGACATGTTGGGCCAGACAACCTAAGTCGCAAGGCGAGAAGTTCTCACTTCTGCTTTTCTCA','L20_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1386392,1386471,'-','CCTCTGTGAAGACTCGCCTATAAATCGTGAGAGCCTTGCCCTACTTAATCTAACGATTTTCGCGCGGTTGCACAGGATG','L21_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,925396,925509,'+','GTGATATACTTAGTAAGTTGTTTTACACAACCCTTGATGCTTAGTTCCCTTTCATCAAGCATATTACAAACGTTAGAAGTGTTAACTATCTAAACGTTAAAGGAGAAATTATG','preQ1-II',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1597644,1597742,'-','AAAAAACCACACTGCTCGGAGTCAATCTCAGCAAACAATGTGGTTTATGGTGGTTTGTTAACTTAAATCATAACAGGTTTGATTTAAACTAACAAATC','23S-methyl',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1318924,1319073,'-','AATAAAACCCCACCAAGATTTAATCTTGGTGGGGTTTTGGTGGGGAATGATAACATTCTCCCGATTTTTTATCGCTCTAAGCAATTCTAAAACCTTGATTTACTAGGCTTCCGCAATCAAATTGCGATACTCTATTATTTAAGAGTAAC','rli38',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,698452,698642,'+','CTTTAATGGTATACTATTAAGTGTAGAAAAGTGAAGACGGTGGTTCCTAAATCCTGAAAGAGAGAGGTGATGCCTATGGGCAATTCATCAAAATCTGATGGAAAGGAGGGAGCTTTCTTTTGACCGCTTTTGAAGTCGTGCAAATCATCATTGGTTTTGGTAGTTTTACCGTTGCTTTGATTGGCTTGTG','rli28',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,90352,90424,'+','GAGTGTTATGATGATGGAATCAATCGATTCTTAGTCTAGCTCTGGTCTACCGCTGAGAATTATTCTCAGCGG','L17DE',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,1119477,1119613,'-','GGAATTACAAGTAGTAGTAAGCTAAGGGCACCTTTTCAAGTGTGATAAGAAGGTTCACACAACTTATCAAGATCCGCTCCTGCGTTCATAATCTCCCTGCGCAATAGTGGTAAAACCACATATCAACTCATCGCAT','asd',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,99777,99875,'+','CGTTATAGCATAAAAACACGTTGCAGTTGGTAGTCTGCAAGCGTTCAGTGAACGTCAGTAACCTTCCCTCCAGGTCGTCCATTGCAATTTAATATTTA','yjdF',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,698943,699032,'-','TTATAGTCTAATTAAACGAGTCACCGTCTTTTTAACGGTCCTACATTGGGGGTTGGATTGCCGTCCAGCTCCTTTTTATAAGTTCATTA','RatA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,698709,698797,'-','GTTATATCGAAATATTGGGTCACCGTCTTTTTAACGGTTCTACATTGGAGTTGAGTTGGTAGCTCAACTCCTTTTTCTACGTTCATTA','RatA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,548696,548841,'-','GTAGCAGATTACCTTGCTGAAGGTGAAAAAGTACAATTAATCGGTTTTGGTAACTTTGAAGTTCGTGAACGTGCAGCTCGTAAAGGTCGTAACCCACAAACTGGTGCAGAAATCGAAATTGCAGCATCAAAAGTTCCAGCATTTA','sau-50',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,2093370,2093436,'-','AACTCTCGAAAATTGTACGTCAAAAAGACTTACAAATTCCATGAACTTTGACCATCATAGTTATTG','Spd-sr37',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,283645,283771,'+','CTGTTTTTTTAGCGAGCTCAAGGTAGTGAAAGTTGGGTAGAATAGGATGAATATTGGCACTTTTTAGTGAGTAAAAGTACAATCAAAAATGAAGTAATAAATTAGGGTGGAACCGCGTCTTTGACG','SpR19_sRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP000114'),2,383794,383922,'-','CTTGTTCTTCCTCCTTAAAAAATTTTTTCGTTGACATAAAGAAGAATAATCTCCTTCCAATCGTAAAATTGGCCATTCTTTTTCATTTCAACGAAATTATAGAACAGATATATTTTAAAACGTTTTCA','SSRC34',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,954430,954779,'-','TATGGAGCCGGTGGGAGTCGAACCCACGTCCAAACATCTGCTAATATATTTGTCTACAACTATAGGTTATGTATTGATTTAACTAGGTGATGACACATAACTCAAGCCCTCACATAGCGAGTCTATAAATCTCTTTTTAACTAACTAGACAGTAGCCAAACGTAGTTTGCTGATAAATAAGACCTTCTAGCAAAACGCAAACAATCTTGTGAAGATCACGCAGGCTGTTTTTTAGGCAGCTAATGCGTAAGAATTTGTATTTTTTGCAGTTATATTTAACTGGCATTTTACATCTGCCGATGAGTCGCGAAATATACCTCATAATGCCTGTCGAATCCGTAACGACCCC','tmRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,771825,771939,'+','AATTTCTTCGGGGTCAGGTGAAAATCCTAACCGGCGGTATAGTCCGCGAGCTTTCGAGCATGAACTGGTGTGATTCCAGTACCGACAGTAAAGTCTGGATGAGAGAAGAATTCA','FMN',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,583002,583046,'-','GTCACTTAGTTTTTTATTCTGGGAAGTTTTCGAACCAGTCCGAG','PreQ1',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,1262494,1262627,'-','TAGGCACAAAAAAATCGCACCTAAACCTAGACACGAAAGTACAATACGTTATTTTATAATGACGTTTTGTGCCTCGGTAGGAATATTATGAGCACTGCTCCCCTACTGTCTTAGGTCAGTTTCATCAGAAACT','L10_leader',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,192430,192487,'+','TTTGTCGTCTGTCTAGGTTGAAATATTGTCCGACCTAGATATACAGCAGTTAAATCA','Lacto-rpoB',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,934848,934952,'-','AAAAAAGCACCGAATCGGTGCTCACTTTTTCAAGCTGAATACGGACTGGATTAAAAATCACTGCCTTATTTTAACGTGCTGTGCTGTTTCGAATAATTCCAACA','tracrRNA',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,324281,324649,'+','TTTTTGGATAATCGCGTAGTATTGAGATACTATGAGGAAAGTCCATGCTAGCACTGGCTGTGATGCCAGTAGTGTTTGTGCTAGGCGAAAAAATAAGCCTAGGGAGATAGCTAGCTATCTTACGGCAAGCAAAAGGGCTAAGTCTTTGGATATGCCTGAATAGCTTTGAAAGTGCCACAGTGACGTAGTTTCTAGGGAAATCTAGAAAGTGGAACGCGGTAAACCCCTCAAGCTAGCAACCCAAACTTTGGTAGGGGCATGGGATAGTTGGAATGAGAACAATCTATCCTGACTGCTTTGCAGTAGACAGATGATTATCGAAAGAAACAATTCCTAGTTGTTTCTGGAACAAAACATGGCTTATAGAA','RNaseP_bact_b',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,1886445,1886636,'+','CATTGCTGTGGCATACGAATCCACATCTAAGTGTTGACCGACTATTTCTTTGTATTTCGGGAAACGAAGTCATCTCTAGTGCGCAAGCCGTTAACACGCGGAAGCCACTTAAAGAGGTGCGAGTTACCCACCTGCTTATTTTGTGCGGGATCAATACAAAAAGTGGATCATCGGTGCCAATACAGCTTCCT','6S',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,98711,98776,'+','ACCGCCGTATGCCGAACGGCACGTACGGTGGTGTGAGAGGGGCTAGAGATTAGCCTCTACTCGAT','Intron_gpII',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,523745,523810,'+','ACCGCCGTATGCCGAACGGCACGTACGGTGGTGTGAGAGGGGCTAGAGATTAGCCTCTACTCGAT','Intron_gpII',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,755471,755536,'+','ACCGCCGTATGCCGAACGGCACGTACGGTGGTGTGAGAGGGGCTAGAGATTAGCCTCTACTCGAT','Intron_gpII',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,1512993,1513058,'-','TCGAGTAGAGGCTAATCTCTAGCCCCTCTCACACCACCGTACGTGCCGTTCGGCATACGGCGGTT','Intron_gpII',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
VALUES((SELECT o.organism_id FROM organism as o WHERE abbreviation like 'CP003810'),2,1565879,1565944,'-','TCGAGTAGAGGCTAATCTCTAGCCCCTCTCACACCACCGTACGTGCCGTTCGGCATACGGCGGTT','Intron_gpII',7,2);
INSERT INTO feature (organism_id,publication_id,start,end,strand,sequence,feature_name,type_type_id,analysis_id) 
