-- MySQL Script generated by MySQL Workbench
-- Sun Jun 18 21:13:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema streptornadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema streptornadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `streptornadb` DEFAULT CHARACTER SET utf8 ;
USE `streptornadb` ;

-- -----------------------------------------------------
-- Table `streptornadb`.`organism`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`organism` (
  `organism_id` INT NOT NULL AUTO_INCREMENT,
  `abbreviation` VARCHAR(255) NOT NULL,
  `genus` VARCHAR(255) NOT NULL,
  `specie` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`organism_id`),
  UNIQUE INDEX `organism_id_UNIQUE` (`organism_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`genbank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`genbank` (
  `genbank_id` INT NOT NULL AUTO_INCREMENT,
  `organism_id` INT NOT NULL,
  `genome` LONGTEXT NOT NULL,
  `genome_version` VARCHAR(45) NULL,
  PRIMARY KEY (`organism_id`),
  UNIQUE INDEX `genbank_id_UNIQUE` (`genbank_id` ASC),
  CONSTRAINT `organism_id_fk`
    FOREIGN KEY (`organism_id`)
    REFERENCES `streptornadb`.`organism` (`organism_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`publication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`publication` (
  `publication_id` INT NOT NULL AUTO_INCREMENT,
  `pubmed_id` VARCHAR(10) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  `pubplace` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`publication_id`),
  UNIQUE INDEX `pubmed_id_UNIQUE` (`pubmed_id` ASC),
  UNIQUE INDEX `publication_id_UNIQUE` (`publication_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`feature` (
  `feature_id` INT NOT NULL AUTO_INCREMENT COMMENT 'TUDO NA APLICAÇÃO É UMA FEATURE, a qual pertecente a um organismo e pode ter sua localização, tipo, grupo, análise, etc.',
  `organism_id` INT NOT NULL,
  `feature_name` VARCHAR(45) NOT NULL,
  `publication_id` INT NOT NULL,
  `start` INT NOT NULL,
  `end` INT NOT NULL,
  `chromossome` VARCHAR(45) NOT NULL,
  `strand` CHAR NOT NULL,
  `sequence` LONGTEXT NOT NULL,
  `precursor_mature` CHAR NOT NULL,
  `candidate_know` CHAR NOT NULL,
  PRIMARY KEY (`feature_id`),
  INDEX `id_organism_idx` (`organism_id` ASC),
  UNIQUE INDEX `feature_id_UNIQUE` (`feature_id` ASC),
  INDEX `publication_id_idx` (`publication_id` ASC),
  CONSTRAINT `id_organism`
    FOREIGN KEY (`organism_id`)
    REFERENCES `streptornadb`.`organism` (`organism_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `publication_id`
    FOREIGN KEY (`publication_id`)
    REFERENCES `streptornadb`.`publication` (`publication_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `group_id_UNIQUE` (`type_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`feature_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`feature_type` (
  `feature_type_id` INT NOT NULL AUTO_INCREMENT,
  `feature_id` INT NOT NULL COMMENT 'Em tipo pode-se tratar mirtron, miRNA, circRNA, etc',
  `type_id` INT NOT NULL,
  PRIMARY KEY (`feature_type_id`, `feature_id`, `type_id`),
  UNIQUE INDEX `feature_type_id_UNIQUE` (`feature_type_id` ASC),
  INDEX `group_classification_fk_idx` (`type_id` ASC),
  INDEX `feature_fk_idx` (`feature_id` ASC),
  CONSTRAINT `group_classification_fk`
    FOREIGN KEY (`type_id`)
    REFERENCES `streptornadb`.`type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `feature_fk`
    FOREIGN KEY (`feature_id`)
    REFERENCES `streptornadb`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`feature_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`feature_relationship` (
  `feature_relationship_id` INT NOT NULL AUTO_INCREMENT,
  `id_feature_source` INT NOT NULL,
  `id_feature_target` INT NOT NULL,
  PRIMARY KEY (`feature_relationship_id`),
  UNIQUE INDEX `feature_relationship_id_UNIQUE` (`feature_relationship_id` ASC),
  UNIQUE INDEX `id_feature_source_UNIQUE` (`id_feature_source` ASC),
  UNIQUE INDEX `id_feature_target_UNIQUE` (`id_feature_target` ASC),
  CONSTRAINT `id_feature_source`
    FOREIGN KEY (`id_feature_source`)
    REFERENCES `streptornadb`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_feature_target`
    FOREIGN KEY (`id_feature_target`)
    REFERENCES `streptornadb`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`analysis_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`analysis_type` (
  `analysis_type_id` INT NOT NULL,
  `analysis_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`analysis_type_id`),
  UNIQUE INDEX `analysis_type_id_UNIQUE` (`analysis_type_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`feature_analysis_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`feature_analysis_result` (
  `feature_analysis_id` INT NOT NULL COMMENT 'Tabela dinamica, número de colunas será incrementado de acordo com o número de análises cadastradas',
  `id_feature` INT NOT NULL,
  `id_analysis_type` INT NOT NULL,
  PRIMARY KEY (`feature_analysis_id`),
  UNIQUE INDEX `feature_analysis_id_UNIQUE` (`feature_analysis_id` ASC),
  INDEX `id_feature_idx` (`id_feature` ASC),
  INDEX `id_analysis_type_idx` (`id_analysis_type` ASC),
  CONSTRAINT `id_feature`
    FOREIGN KEY (`id_feature`)
    REFERENCES `streptornadb`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_analysis_type`
    FOREIGN KEY (`id_analysis_type`)
    REFERENCES `streptornadb`.`analysis_type` (`analysis_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`group` (
  `group_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Em grupo pode-se tratar as regiões de RNA',
  `group_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`feature_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`feature_group` (
  `feature_group_id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `feature_id` INT NOT NULL,
  PRIMARY KEY (`feature_group_id`),
  INDEX `group_id_fk_idx` (`group_id` ASC),
  INDEX `feature_id_fk_idx` (`feature_id` ASC),
  CONSTRAINT `group_id_fk`
    FOREIGN KEY (`group_id`)
    REFERENCES `streptornadb`.`group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `feature_id_fk`
    FOREIGN KEY (`feature_id`)
    REFERENCES `streptornadb`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`localization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`localization` (
  `loc_id` INT NOT NULL AUTO_INCREMENT,
  `loc_identification` VARCHAR(45) NOT NULL,
  `host_gene` VARCHAR(45) NOT NULL,
  `sequence` LONGTEXT NOT NULL,
  `start` INT NOT NULL,
  `end` INT NOT NULL,
  `strand` CHAR NOT NULL,
  PRIMARY KEY (`loc_id`),
  UNIQUE INDEX `feature_loc_id_UNIQUE` (`loc_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streptornadb`.`featureloc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streptornadb`.`featureloc` (
  `featureloc_id` INT NOT NULL AUTO_INCREMENT,
  `loc_id` INT NOT NULL,
  `feature_id` INT NOT NULL,
  PRIMARY KEY (`featureloc_id`),
  INDEX `featureloc_fk_idx` (`loc_id` ASC),
  INDEX `featureidloc_fk_idx` (`feature_id` ASC),
  CONSTRAINT `featureloc_fk`
    FOREIGN KEY (`loc_id`)
    REFERENCES `streptornadb`.`localization` (`loc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `featureidloc_fk`
    FOREIGN KEY (`feature_id`)
    REFERENCES `streptornadb`.`feature` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
